name: Quorra Custom Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest, windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev libsndfile1-dev libfaiss-dev
        sudo apt-get install -y build-essential swig

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyaudio faiss-cpu

    - name: Install project requirements
      run: |
        pip install -r requirements.txt
